os:
  - linux
  
services:
  - docker

language: node_js

node_js:
  - "6.9"

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  - node_modules

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot=false
  - ng test --watch false --log-level verbose
  - ng e2e

notifications:
  email:
    on_failure: change
    on_success: change
    
deploy:
  provider: codedeploy
  wait-until-deployed: true
  access_key_id: 'AKIAJ4VMDB2COFFJJHXA'
  secret_access_key: 'SamFxY3embI4WIbDYl8IrJRFYGLPxpxghw3AOljAehN7thjr6xMVzjVcDqjVGTfEXXeM3/93OY3KK33bec/nXDwLB9RFhbIkjmVFQAxnRuAth6Voob0fu/3+ugWubxiKGeZtor1VyByvULb2boYGuYLqGT1Dhz0e+700Dw48tJMMjimi1YwG8S7rhO1KH7EfoLkqu+pWcatbKaRzuYxk70zR6MAGeuWJwP/p+laoldgS+nWhM07EEKP9EkHcGnBvxTd8/aLHJy6WQdZOqM7U1YxciEidW19VP5x0mpHIjVBwuoo0mjrPSldgqpfwl/oXwqVDJ0FQxlOqPmYJyCBHAMHY9SoSN0wPniztqNEXeF++3xHmb+eCnLii5ZWHelYe7bZBP/xltpAoVpznXyK0bJTyaEqbQHthymSqguaZOk+l0LwqUGrwIb25qDVvljnv2Tu35rphWNvO+oNKnSDHsxWxmnP42mOsJLvfCB2kJ3pqgVy12zGkFzIQhjGLImapzUH8wTm5d7xgwAJd0prSI6FyiG38eUpUIICWOzw4ZUIf3sRh+jatDVIC3iNMCAky1320XyCktj97Q8bGqjAu1qDVSBzFTn1kuAGfaeEmeJSnlKHVY5XGjm96VVdgOaYZZGkHsDma8zUDbT1RE2aJHpNoqzCSaTrcqwV9TuNSU6Y='
  application: LSDDemoApplication
  deployment_group: LSDDemoFleet-fqa7sfz
  region: eu-central-1
  on:
    all_branches: true