os:
  - linux

language: node_js

node_js:
  - "6.9"

cache:
  - node_modules

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot=false
  - ng test --watch false --log-level verbose

notifications:
  email:
    on_failure: change
    on_success: change
