os:
  - linux
  
services:
  - docker

language: node_js

node_js:
  - "6.9"

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  - node_modules

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot=false
  - ng test --watch false --log-level verbose
  - ng e2e

notifications:
  email:
    on_failure: change
    on_success: change
