version: 0.0
os: linux
files:
  - source: /
    destination: ~/deployment_folder
hooks:
  BeforeInstall:
    - location: scripts/install_apache
      timeout: 300
      runas: root
    - location: scripts/install_node
      timeout: 300
      runas: root
    - location: scripts/start_apache
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/setup_project
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_apache
      timeout: 300
      runas: root

