#!/bin/bash
yum install -y httpd

# Install Node JS
curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
yum -y install nodejs

echo "Installing dependencies"
cd /var/www/html
npm install

echo "Installing Angular CLI"
npm install -g @angular/cli

echo "Building"
ng build --prod --aot=false
